name: Build, Push and Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: wide-net-466915-c6
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker europe-central2-docker.pkg.dev

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: europe-central2-docker.pkg.dev/wide-net-466915-c6/docker-test-repository/producer:latest

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: docker-test-cluster      
        location: us-central1       

    - name: Deploy to GKE
      run: |
        kubectl set image deployment/producer-deployment \
          producer-container=europe-central2-docker.pkg.dev/wide-net-466915-c6/docker-test-repository/producer:latest
